
spring:
  mail:
    port: 587
    host: smtp.qq.com
    username: 271724646@qq.com
    password:
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


server:
  port: 8080
