server:
  port: 8081
spring:
  jpa:
    properties:
      hibernate:
         hbm2ddl:
           auto: update
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置数据库方言
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      #配置获取连接等待超时的时间
      max-wait: 6000
      #检测连接是否有效的sql
      validation-query: "select '1'"
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 600000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      remove-abandoned: true
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-2ze6dvrqezp7j30g6zo.mysql.rds.aliyuncs.com:3306/qingchen?useUnicode=true&characterEncoding=utf8
      username: wangchen
      password: Kvalue_wangchen
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-2ze6dvrqezp7j30g6zo.mysql.rds.aliyuncs.com:3306/qingchen-slave?useUnicode=true&characterEncoding=utf8
      username: wangchen
      password: Kvalue_wangchen


