spring:
  rabbitmq:
    host: 123.57.84.238
    port: 5672
    username: wangchen
    password: wangchen
    virtual-host: /
    #消息发送确认
    publisher-confirms: true
    #消息发送失败退回
    publisher-returns: true
    listener:
      simple:
        default-requeue-rejected: true
        #最小并发数
        concurrency: 1
        #最大并发数
        max-concurrency: 5
        #RabbitMQ提供了一种QOS(服务质量保证)功能，即在非自动确认的消息的前提下，限制信道上的消费者所能保持的最大未确认的数量
        #一次请求中预处理的消息数量
        prefetch: 2
        #手动应答
        acknowledge-mode: manual




